best3.pth:
  build_time: 2021-02-20-17-51-50
  labels:
    blocked: 182
    free: 86
  loader:
    batch_size: 8
    num_workers: 0
    shuffle: true
  purpose: classifier
  train:
    accuracy: 1.0
    epochs: 10
    learning_rate: 0.001
    model: alexnet
    momentum: 0.09
    train_time: 254.53
    use_cuda: true
