best.pth:
  build_time: 2020-12-16-11-23-33
  labels:
    blocked: 145
    free: 126
  loader:
    batch_size: 8
    num_workers: 0
    shuffle: true
  train:
    accuracy: 1.0
    epochs: 1
    learning_rate: 0.001
    model: alexnet
    momentum: 0.09
    train_time: 183.77
    use_cuda: true
